#!/usr/bin/env python3
"""Convert a published grid-map image into a `map_server` map pair.

Several of the standard 2D SLAM benchmark maps are distributed as an image and
nothing else: a PNG in which walls are dark, explored floor is white and the
never-observed background is a flat mid grey, with no accompanying metadata. The
image is a perfectly good occupancy grid, but the rest of this project's
pipeline — `map_to_world.py` above all — consumes the `map_server` pair
(`<stem>.pgm` + `<stem>.yaml`), which additionally carries the resolution and the
origin.

This tool supplies the missing half. It quantises the image into the three
values `map_server` recognises

    254   free
    205   unknown
      0   occupied

using two thresholds, and writes the YAML alongside with the resolution given on
the command line. Nothing is rescaled or resampled: one source pixel is one
cell, so the geometry that reaches Gazebo is the geometry that was published.

The middle grey band matters. A published map's background is uniform because it
was never observed, whereas the grey immediately outside a wall is genuine
partial evidence from beams that stopped short. Thresholding both into
'occupied' would wrap the building in a shell of phantom wall; thresholding both
into 'unknown' is correct and is what the default thresholds do, because
`map_to_world.py` derives its walls from the *free* mask anyway.

    python3 tools/png_to_map.py FR079.png -o src/mrs_bringup/maps/fr079 \\
        --resolution 0.05
"""

import argparse
import os
import sys

import numpy as np
from PIL import Image


YAML_TEMPLATE = """# GENERATED by tools/png_to_map.py from {source} - do not edit by hand.
#
# Values follow the map_server convention: 254 free, 205 unknown, 0 occupied,
# with `negate: 0` so that occupancy is (255 - value) / 255.
image: {image}
resolution: {resolution}
origin: [{ox}, {oy}, 0.0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196
"""


def convert(image_path, free_above, occupied_below):
    image = Image.open(image_path)
    array = np.array(image.convert('L'))

    out = np.full(array.shape, 205, dtype=np.uint8)
    out[array >= free_above] = 254
    out[array <= occupied_below] = 0
    return out, array


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('image', help='source image (PNG, PGM, ...)')
    parser.add_argument('-o', '--output', required=True,
                        help='destination stem; writes <stem>.pgm and <stem>.yaml')
    parser.add_argument('--resolution', type=float, required=True,
                        help='metres per pixel of the source image')
    parser.add_argument('--origin', type=float, nargs=2, default=(0.0, 0.0),
                        metavar=('X', 'Y'),
                        help='world coordinates of the lower-left cell')
    parser.add_argument('--free-above', type=int, default=241,
                        help='grey level at or above which a pixel is free')
    parser.add_argument('--occupied-below', type=int, default=100,
                        help='grey level at or below which a pixel is occupied')
    args = parser.parse_args(argv)

    cells, source = convert(args.image, args.free_above, args.occupied_below)

    stem = args.output
    pgm_path = stem + '.pgm'
    yaml_path = stem + '.yaml'
    os.makedirs(os.path.dirname(os.path.abspath(stem)), exist_ok=True)

    Image.fromarray(cells).save(pgm_path)
    with open(yaml_path, 'w') as handle:
        handle.write(YAML_TEMPLATE.format(
            source=os.path.basename(args.image),
            image=os.path.basename(pgm_path),
            resolution=args.resolution,
            ox=args.origin[0], oy=args.origin[1]))

    free = int((cells == 254).sum())
    occupied = int((cells == 0).sum())
    unknown = int((cells == 205).sum())
    area = free * args.resolution ** 2
    print(f'{pgm_path}: {cells.shape[1]}x{cells.shape[0]} cells at '
          f'{args.resolution} m, {free} free ({area:.1f} m2), '
          f'{occupied} occupied, {unknown} unknown; '
          f'source grey levels {source.min()}..{source.max()}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
