#include "warehouse_tools/problem_writer.hpp"

#include <algorithm>
#include <limits>
#include <sstream>
#include <stdexcept>

namespace warehouse_tools
{

Scenario buildScenario(const Roadmap & roadmap, int n_robots, int n_crates)
{
  if (n_robots < 1 || n_crates < 1) {
    throw std::runtime_error("a scenario needs at least one robot and one crate");
  }

  Scenario scenario;
  scenario.docks = roadmap.namesOfKind(WaypointKind::Dock);
  const auto bays = roadmap.namesOfKind(WaypointKind::Storage);
  auto corridors = roadmap.namesOfKind(WaypointKind::Corridor);
  if (scenario.docks.empty() || bays.empty() || corridors.empty()) {
    throw std::runtime_error("the roadmap needs at least one dock, bay and corridor node");
  }

  // Greedy farthest-point over *graph* travel time. Spreading the fleet by
  // Euclidean distance would put two robots on opposite sides of a shelf and
  // call them far apart, which is precisely the mistake the roadmap exists to
  // stop the rest of the workspace making.
  std::vector<std::string> starts{corridors.front()};
  while (static_cast<int>(starts.size()) < n_robots) {
    std::string best;
    double best_distance = -1.0;
    for (const auto & candidate : corridors) {
      if (std::find(starts.begin(), starts.end(), candidate) != starts.end()) {
        continue;
      }
      double nearest = std::numeric_limits<double>::infinity();
      for (const auto & chosen : starts) {
        nearest = std::min(nearest, roadmap.shortestTime(candidate, chosen));
      }
      if (nearest > best_distance) {
        best_distance = nearest;
        best = candidate;
      }
    }
    if (best.empty()) {
      break;      // fewer corridor nodes than robots; fall through to reuse
    }
    starts.push_back(best);
  }
  // A fleet larger than the corridor graph is a legitimate configuration — two
  // robots can start on the same node — and is reported honestly rather than
  // refused, since it is the configuration in which congestion shows up first.
  while (static_cast<int>(starts.size()) < n_robots) {
    starts.push_back(corridors[starts.size() % corridors.size()]);
  }

  for (int i = 0; i < n_robots; ++i) {
    scenario.robots.push_back("r" + std::to_string(i + 1));
    scenario.robot_start.push_back(starts[static_cast<size_t>(i)]);
  }
  for (int i = 0; i < n_crates; ++i) {
    scenario.crates.push_back("crate" + std::to_string(i + 1));
    scenario.crate_bay.push_back(bays[static_cast<size_t>(i) % bays.size()]);
  }
  return scenario;
}

std::string writeProblem(
  const Roadmap & roadmap,
  const Scenario & scenario,
  const std::string & problem_name)
{
  std::ostringstream out;
  out.setf(std::ios::fixed);
  out.precision(1);

  out << ";; GENERATED by warehouse_tools/problem_generator - do not edit by hand.\n"
      << ";; " << scenario.robots.size() << " robot(s), " << scenario.crates.size()
      << " crate(s), " << roadmap.waypoints().size() << " waypoints, "
      << roadmap.edges().size() << " undirected edges.\n"
      << "(define (problem " << problem_name << ")\n(:domain warehouse)\n";

  out << "(:objects\n  ";
  for (const auto & r : scenario.robots) {
    out << r << ' ';
  }
  out << "- robot\n  ";
  for (const auto & wp : roadmap.waypoints()) {
    out << wp.name << ' ';
  }
  out << "- waypoint\n  ";
  for (const auto & c : scenario.crates) {
    out << c << ' ';
  }
  out << "- crate\n)\n";

  out << "(:init\n";
  for (size_t i = 0; i < scenario.robots.size(); ++i) {
    out << "  (robot_at " << scenario.robots[i] << ' ' << scenario.robot_start[i] << ")\n"
        << "  (gripper_free " << scenario.robots[i] << ")\n";
  }
  for (size_t i = 0; i < scenario.crates.size(); ++i) {
    out << "  (crate_at " << scenario.crates[i] << ' ' << scenario.crate_bay[i] << ")\n";
  }
  for (const auto & dock : scenario.docks) {
    out << "  (is_dock " << dock << ")\n  (dock_free " << dock << ")\n";
  }
  // The roadmap is undirected and the domain is directed: both directions are
  // asserted, and both carry the same duration, because the vehicle's cost of
  // driving an edge does not depend on which end it starts from.
  for (const auto & edge : roadmap.edges()) {
    out << "  (connected " << edge.from << ' ' << edge.to << ")\n"
        << "  (connected " << edge.to << ' ' << edge.from << ")\n"
        << "  (= (travel_time " << edge.from << ' ' << edge.to << ") "
        << edge.travel_time_s << ")\n"
        << "  (= (travel_time " << edge.to << ' ' << edge.from << ") "
        << edge.travel_time_s << ")\n";
  }
  out << ")\n";

  out << "(:goal (and\n";
  for (const auto & c : scenario.crates) {
    out << "  (delivered " << c << ")\n";
  }
  out << "))\n(:metric minimize (total-time))\n)\n";
  return out.str();
}

}  // namespace warehouse_tools
